name: CircleCi_TO_GithubActions

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:
        inputs:
            run_tests:
                description: Run tests
                required: true
                default: true
                type: boolean

jobs:
    job_test:
        runs-on: ubuntu-latest
        container:
            image: cimg/node:20.14.0
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Show node version
              run: node --version
            - name: Run test in Docker
              run: npm ci && npm test
      