name: Run 3 Jobs

on: 
    workflow_dispatch:
        inputs:
            run_jobs_2:
                description: "Have to run 3 jobs"
                required: true 
                type: boolean

jobs: 
    job-1:
        name: "Run Job 1"
        runs-on: ubuntu-latest
        steps: 
            - name: "Run Job"
              run: echo "Job 1 completed. Run Job 2 equals ${{ github.event.inputs.run_jobs_2}}"

    job-2: 
        name: "Run Job 2"
        runs-on: ubuntu-latest
        needs: job-1
        steps: 
            - name: "Run Job"
              run: echo "Job 2 completed"

    job-3: 
        name: "Run Job 3"
        runs-on: ubuntu-latest
        needs: job-2
        steps:
            - name: "Run Job"
              run: echo "Job 3 completed"